# Generated by Django 5.2.14 on 2026-06-06 07:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'consumable family',
                'verbose_name_plural': 'consumable families',
                'db_table': 'consumables_family',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('compatible_devices', models.JSONField(blank=True, default=list)),
                ('recommended_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_lifetime', models.CharField(blank=True, max_length=100, null=True)),
                ('replacement_cycle', models.CharField(blank=True, max_length=100, null=True)),
                ('current_stock', models.IntegerField(default=1)),
                ('low_stock_threshold', models.IntegerField(default=1)),
                ('purchase_link', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables', to='consumables.consumablefamily')),
            ],
            options={
                'verbose_name': 'consumable',
                'verbose_name_plural': 'consumables',
                'db_table': 'consumables_consumable',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('replaced_at', models.DateTimeField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_usages', to='assets.asset')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='consumables.consumable')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumable_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usage record',
                'verbose_name_plural': 'usage records',
                'db_table': 'consumables_usagerecord',
                'ordering': ['-replaced_at'],
            },
        ),
    ]
